Change base docker image
Tknika/iombian-shutdown-service pull request #3
Opened 2024-03-12 19:44 UTC by aitorcas23

Change base python docker image because of incompatibilities in some packages in raspbian 11.

Couldn't execute systemctl reboot or poweroff because from inside the container.

2024-03-12 20:47 UTC, bodiroga requested changes

2024-03-12 20:47 UTC, bodiroga commented on src/main.py
> +SHUTDOWN_PORT = int(os.environ.get("SHUTDOWN_PORT", 5558))
@aitorcas23, ok, mejor nada que 'events', pero creo que lo idea sería que estas variables se llamaran "SHUTDOWN_SERVICE_HOST" y "SHUTDOWN_SERVICE_PORT"

2024-03-12 20:47 UTC, bodiroga commented on src/main.py
> +    server = CommunicationServer(shutdown_commans, host=SHUTDOWN_HOST, port=SHUTDOWN_PORT)
```suggestion
    server = CommunicationServer(shutdown_commands, host=SHUTDOWN_HOST, port=SHUTDOWN_PORT)
```

@aitorcas23, se acaba de colar de nuevo el "commans", aunque esta vez la definición de la variable es correcta 😜

2024-03-12 20:47 UTC, bodiroga commented on src/shutdown_commands.py
> +        logging.debug("shutdown command recieved.")
@aitorcas23, entiendo la idea, pero creo que el mensaje no es adecuado, lo siento. Esta clase no sabe nada sobre ningún comando/evento, su única función es apagar/reiniciar el dispositivo cuando llamen a sus funciones. El que sabe sobre los comandos es el CommunicationServer y ahí sí que imprimimos un mensaje en el log cuando se recibe un comando ```logger.debug(f"Command '{req_command}' has been requested")```. Si quieres añadir un mensaje aquí, yo optaría por:

```suggestion
        logging.debug("Shutting down the device.")
```

2024-03-12 20:47 UTC, bodiroga commented on src/shutdown_commands.py
> +        logging.debug("reboot command recieved.")
```suggestion
        logging.debug("Rebooting the device.")
```

2024-03-16 12:49 UTC, aitorcas23 commented on src/main.py
> +SHUTDOWN_PORT = int(os.environ.get("SHUTDOWN_PORT", 5558))
Ok, me parece bien, cambiaré todos los shutdown host y port de otros servicios también por consistencia.

2024-03-16 22:08 UTC, bodiroga approved these changes
LGTM! 👍🏻

2024-03-16 22:10 UTC, merged